<select>
    <option value="select">Choisir un Tehilim</option>
    <option value="custom">Liste de tehilim personnalisée</option>
    <option value="tehilim-0"> Prière avant de lire les tehilim </option>
    <option value="tehilim-1">1. Pour prévenir d'une fausse couche </option>
    <option value="tehilim-2">2. Contre une tempête en mer et le mal de tête </option>
    <option value="tehilim-3">3. Pour le mal à l'épaule ou à la tête. </option>
    <option value="tehilim-4">4. En toutes occasions. </option>
    <option value="tehilim-5">5. Pour empêcher le mauvais esprit </option>
    <option value="tehilim-6">6. Ceux qui souffrent des yeux. ( A lire sept fois durant trois jours). </option>
    <option value="tehilim-7">7. Pour repousser ses ennemis </option>
    <option value="tehilim-8">8. Trouver grâce devant une autorité. </option>
    <option value="tehilim-9">9. Pour un enfant malade. </option>
    <option value="tehilim-10">10. Contre ses ennemis. </option>
    <option value="tehilim-11">11. Pour détruire ses ennemis </option>
    <option value="tehilim-12">12. Contre la faiblesse. </option>
    <option value="tehilim-13">13. Pour échapper à une mort violente. </option>
    <option value="tehilim-14">14. Contre la peur. </option>
    <option value="tehilim-15">15. Pour tuer un démon et un mauvais esprit. </option>
    <option value="tehilim-16">16. Pour découvrir un voleur </option>
    <option value="tehilim-17">17. Pour prendre la route. </option>
    <option value="tehilim-18">18. Pour se protéger contre les hommes mauvais. </option>
    <option value="tehilim-19">19. Pour la Sagesse et la bonté. </option>
    <option value="tehilim-20">20. Pour les malades </option>
    <option value="tehilim-21">21. Avant d'aller devant une autorité </option>
    <option value="tehilim-22">22. Contre le chagrin. </option>
    <option value="tehilim-23">23. Pour expliquer un rêve. </option>
    <option value="tehilim-24">24. Pour être sauvé d'une inondation </option>
    <option value="tehilim-25">25. Conjurer le malheur </option>
    <option value="tehilim-26">26. Contre le danger et le malheur. </option>
    <option value="tehilim-27">27. Contre les bêtes sauvages </option>
    <option value="tehilim-28">28. Pour qu’une prière soit acceptée </option>
    <option value="tehilim-29">29. Pour prier contre l'esprit du mal. </option>
    <option value="tehilim-30">30. Contre toutes les mauvaises choses </option>
    <option value="tehilim-31">31. Contre le mauvais oeil </option>
    <option value="tehilim-32">32. Pour demander miséricorde </option>
    <option value="tehilim-33">33. Pour une mère qui a perdu ses enfants. </option>
    <option value="tehilim-34">34. Pendant la route </option>
    <option value="tehilim-35">35. Contre ses rivaux et des gens venus se disputer. </option>
    <option value="tehilim-36">36. Pour détruire les méchants. </option>
    <option value="tehilim-37">37. Pour une location et pour faire passer un moment d'ivresse </option>
    <option value="tehilim-38">38. Contre les mauvais conseils et les mauvaises paroles des gens sur nous. </option>
    <option value="tehilim-39">39. Pour celui qui jeûne </option>
    <option value="tehilim-40">40. Pour échapper à un mauvais esprit </option>
    <option value="tehilim-41">41. Pour ne pas perdre son emploi </option>
    <option value="tehilim-42">42. Avant de construire une maison </option>
    <option value="tehilim-43">43. Avant de construire une maison. </option>
    <option value="tehilim-44">44. Pour échapper à un mauvais esprit. </option>
    <option value="tehilim-45">45. Pour celui qui a une épouse méchante </option>
    <option value="tehilim-46">46. Si un homme hait sa femme </option>
    <option value="tehilim-47">47. Pour faire pénitence. </option>
    <option value="tehilim-48">48. Pour faire peur à ses ennemis. </option>
    <option value="tehilim-49">49. Contre la fièvre. </option>
    <option value="tehilim-50">50. Pour échapper aux brigands. </option>
    <option value="tehilim-51">51. Contre un débauché </option>
    <option value="tehilim-52">52. Contre la tentation de la médisance </option>
    <option value="tehilim-53">53. Pour faire peur à ses ennemis. </option>
    <option value="tehilim-54">54. Pour se venger de ses ennemis </option>
    <option value="tehilim-55">55. Contre toutes les mauvaises choses </option>
    <option value="tehilim-56">56. Pour un détenu </option>
    <option value="tehilim-57">57. Pour la réussite </option>
    <option value="tehilim-58">58. Contre un chien méchant. </option>
    <option value="tehilim-59">59. Contre le Mauvais Penchant. </option>
    <option value="tehilim-60">60. Pour aller en Guerre </option>
    <option value="tehilim-61">61. Pour celui qui a peur de rester à la maison </option>
    <option value="tehilim-62">62. Après les prières de Minha et Arvit </option>
    <option value="tehilim-63">63. Pour réussir dans les affaires </option>
    <option value="tehilim-64">64. Avant de traverser une rivière </option>
    <option value="tehilim-65">65. Pour obtenir quelque chose de quelqu’un </option>
    <option value="tehilim-66">66. Pour un possédé du démon </option>
    <option value="tehilim-67">67. Contre une fièvre persistante </option>
    <option value="tehilim-68">68. Contre le mauvais esprit </option>
    <option value="tehilim-69">69. Pour un homme cupide et débauché </option>
    <option value="tehilim-70">70. En temps de guerre </option>
    <option value="tehilim-71">71. Pour plaire </option>
    <option value="tehilim-72">72. Pour trouver grâce </option>
    <option value="tehilim-73">73. Pour conjurer la haine </option>
    <option value="tehilim-74">74. Si vous craignez des ennemis </option>
    <option value="tehilim-75">75. Pour éliminer l’orgueil </option>
    <option value="tehilim-76">76. Pour échapper à l’eau et au feu </option>
    <option value="tehilim-77">77. Pour se protéger de toute souffrance </option>
    <option value="tehilim-78">78. Pour trouver grâce devant les autorités </option>
    <option value="tehilim-79">79. Pour vaincre des ennemis </option>
    <option value="tehilim-80">80. Pour se protéger de l’idolâtrie </option>
    <option value="tehilim-81">81. Pour se protéger de l’idolâtrie </option>
    <option value="tehilim-82">82. Pour celui qui perd ses membres </option>
    <option value="tehilim-83">83. En cas de guerre </option>
    <option value="tehilim-84">84. Pour un malade qui maigrit </option>
    <option value="tehilim-85">85. Pour contenter un ami </option>
    <option value="tehilim-86">86. Pour échapper à un mauvais sort </option>
    <option value="tehilim-87">87. Pour sauver la ville </option>
    <option value="tehilim-88">88. Pour sauver la ville ou une assemblée </option>
    <option value="tehilim-89">89. Pour celui qui perd ses membres </option>
    <option value="tehilim-90">90. Pour échapper à un lion </option>
    <option value="tehilim-91">91. Contre un mauvais esprit </option>
    <option value="tehilim-92">92. Pour assister à de grands miracles </option>
    <option value="tehilim-93">93. Pour gagner un procès </option>
    <option value="tehilim-94">94. Si votre ennemi vous poursuit </option>
    <option value="tehilim-95">95. Pour ne pas être trompé par les gens </option>
    <option value="tehilim-96">96. Pour réjouir sa famille </option>
    <option value="tehilim-97">97. Pour réjouir sa famille </option>
    <option value="tehilim-98">98. Pour faire la paix avec son prochain </option>
    <option value="tehilim-99">99. Pour avoir la foi </option>
    <option value="tehilim-100">100. Pour vaincre son ennemi </option>
    <option value="tehilim-101">101. Contre un mauvais esprit </option>
    <option value="tehilim-102">102. Pour avoir des enfants </option>
    <option value="tehilim-103">103. Pour avoir des enfants </option>
    <option value="tehilim-104">104. Pour éloigner une chose nuisible </option>
    <option value="tehilim-105">105. Maladie qui récidive une quatrième fois </option>
    <option value="tehilim-106">106. Maladie qui récidive une troisième fois </option>
    <option value="tehilim-107">107. Contre une maladie persistante </option>
    <option value="tehilim-108">108. Pour la réussite </option>
    <option value="tehilim-109">109. Si votre ennemi vous poursuit </option>
    <option value="tehilim-110">110. Pour faire la paix avec son ennemi </option>
    <option value="tehilim-111">111. Pour se faire des amis </option>
    <option value="tehilim-112">112. Pour devenir fort et puissant </option>
    <option value="tehilim-113">113. Contre l’hérésie </option>
    <option value="tehilim-114">114. Avant d’acheter et de vendre </option>
    <option value="tehilim-115">115. Avant de discuter avec ses pareil </option>
    <option value="tehilim-116">116. Pour échapper à une mort violente </option>
    <option value="tehilim-117">117. Si on vous a dénoncé à tort </option>
    <option value="tehilim-118">118. Avant de répondre à un mécréant </option>
    <option value="tehilim-119">119. Avant d’accomplir une mitsva </option>
    <option value="tehilim-120">120. Pour faire la paix </option>
    <option value="tehilim-121">121. Bon pour la guérison </option>
    <option value="tehilim-122">122. Avant de rencontrer un homme important </option>
    <option value="tehilim-123">123. Pour un esclave en fuite </option>
    <option value="tehilim-124">124. Pour une traversée en bateau </option>
    <option value="tehilim-125">125. Contre les ennemis </option>
    <option value="tehilim-126">126. Pour une femme qui a perdu ses enfants </option>
    <option value="tehilim-127">127. Pour un bêbé qui vient de naître </option>
    <option value="tehilim-128">128. Pour une femme enceinte </option>
    <option value="tehilim-129">129. Pour une mitsva </option>
    <option value="tehilim-130">130. Avant une traversée en bateau </option>
    <option value="tehilim-131">131. Contre l’orgueilleux </option>
    <option value="tehilim-132">132. Pour tenir ses serments </option>
    <option value="tehilim-133">133. Pour inspirer l’amitié </option>
    <option value="tehilim-134">134. A dire avant l’étude </option>
    <option value="tehilim-135">135. Contre les pensées hérétiques </option>
    <option value="tehilim-136">136. Pour avouer ses fautes </option>
    <option value="tehilim-137">137. Pour conjurer la Haine </option>
    <option value="tehilim-138">138. Pour lutter contre l’orgueil </option>
    <option value="tehilim-139">139. Pour ramener l’amour entre mari et femme </option>
    <option value="tehilim-140">140. Contre la haine entre mari et femme </option>
    <option value="tehilim-141">141. Contre les douleurs du coeur </option>
    <option value="tehilim-142">142. Pour ceux qui souffrent des cuisses </option>
    <option value="tehilim-143">143. Pour ceux qui souffrent des bras </option>
    <option value="tehilim-144">144. Pour celui qui s’est brisé une main </option>
    <option value="tehilim-145">145. Contre la peur </option>
    <option value="tehilim-146">146. Pour se protéger des coups d’épée </option>
    <option value="tehilim-147">147. Contre La morsure du serpent </option>
    <option value="tehilim-148">148. Contre un incendie </option>
    <option value="tehilim-149">149. Contre La propagation d’un incendie </option>
    <option value="tehilim-150">150. Pour louer Le Saint Béni soitIl dans toutes ses actions </option>
    <option value="tehilim-151"> Prière après la lecture des tehilim </option>
</select>